In [1]:
import numpy as np

# Questions 1:

## Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [2]:
np_arr = np.arange(2, 50, 3)

print(np_arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


---

# Questions 2:
## Accept two lists of 5 elements each from the user.
## Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [5]:
arr_1 = np.array([int(input()) for i in range(5)])
arr_2 = np.array([int(input()) for i in range(5)])

print(np.sort(np.concatenate((arr_1, arr_2))))

56
70
30
98
81
3
12
20
45
1
[ 1  3 12 20 30 45 56 70 81 98]


---

# Questions 3:

## Write a code snippet to find the dimensions of a ndarray and its size.


In [7]:
arr = np.arange(1, 10, 1)

print(arr.ndim)
print(arr.size)

1
9


---

# Questions 4:
## How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [10]:
arr = np.arange(1, 10)

### Using np.newaxis for converting 1D array to 2D array

In [11]:
# Converting 1D array to a 2D Row Vector
arr_row = arr[np.newaxis, :]
print(arr_row)

[[1 2 3 4 5 6 7 8 9]]


In [12]:
# Converting 1D array to a 2D Column Vector
arr_col = arr[:, np.newaxis]
print(arr_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


### Using np.expand_dims for converting 1D array to 2D array

In [13]:
# Converting 1D array to a 2D Row Vector
arr_row_expand = np.expand_dims(arr, axis = 0)
print(arr_row_expand)

[[1 2 3 4 5 6 7 8 9]]


In [14]:
# Converting 1D array to a 2D Column Vector
arr_col_expand = np.expand_dims(arr, axis = 1)
print(arr_col_expand)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


---

# Questions 5:
## Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [17]:
sq_1 = np.random.random((3, 3))
sq_2 = np.random.random((3, 3))

print(sq_1)
print(sq_2)

[[0.48223428 0.1250958  0.92487064]
 [0.4372092  0.19064054 0.49006218]
 [0.87165567 0.37661188 0.10026891]]
[[0.31142011 0.71953375 0.44824936]
 [0.95086911 0.85320812 0.03807432]
 [0.54119387 0.98399327 0.27889585]]


### Stacking arrays in sequence vertically (row wise) using np.vstack()

In [19]:
print(np.vstack((sq_1, sq_2)))

[[0.48223428 0.1250958  0.92487064]
 [0.4372092  0.19064054 0.49006218]
 [0.87165567 0.37661188 0.10026891]
 [0.31142011 0.71953375 0.44824936]
 [0.95086911 0.85320812 0.03807432]
 [0.54119387 0.98399327 0.27889585]]


### Stacking arrays in sequence horizontially (column wise) using np.hstack()

In [20]:
print(np.hstack((sq_1, sq_2)))

[[0.48223428 0.1250958  0.92487064 0.31142011 0.71953375 0.44824936]
 [0.4372092  0.19064054 0.49006218 0.95086911 0.85320812 0.03807432]
 [0.87165567 0.37661188 0.10026891 0.54119387 0.98399327 0.27889585]]


---

# Questions 6:
## How to get unique items and counts of unique items?

np.unique() is used to find unique elements in an numpy array. Returns the elements in the sorted form.

#### Syntax : np.unique(nparray, return_counts = True)
return_counts : Optional argument. Returns the number of times an item appears in an array

In [21]:
arr = np.arange(1, 20, 2)
print(arr)

u, count = np.unique(arr, return_counts = True)
print(u)
print(count)

[ 1  3  5  7  9 11 13 15 17 19]
[ 1  3  5  7  9 11 13 15 17 19]
[1 1 1 1 1 1 1 1 1 1]
